### ISSUE TITLE
Mistakes in Translations

### ISSUE THREAD

**Issue by JonathanZhang0813** [NetLogo-Mobile/Translation-Chinese#36]
I am 书呆子 from the Chinese site of TurtleUniverse or Book-eater from the Global site. There are many mistakes in the translations of the models such as "怎么这个模型是怎么运行的" and "如何这个模型怎么用". These are some of the mistakes in the translations of the models.

**Comment by CIVITAS-John** [comment]
Hello, 

如果你发现有问题，可以直接在这个repo里修改，并且提交 pull request

**Comment by CIVITAS-John** [comment]
Thanks! I am closing this one now.
